### Installing numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


### Importing the library

In [2]:
import numpy as np

### Defining an array

In [4]:
x = np.array([1, 2, 3, 4])
print(x)

[1 2 3 4]


#### Array of zeros

In [7]:
z_array=np.zeros((2,2))
print("Zeros Array:\n",z_array)

Zeros Array:
 [[0. 0.]
 [0. 0.]]


#### Array of ones 

In [8]:
o_array=np.ones((2,2))
print("Ones array:\n",o_array)

Ones array:
 [[1. 1.]
 [1. 1.]]


#### Range specified arrays

In [9]:
x=np.arange(0,10,2)
print("range array",x)

range array [0 2 4 6 8]


In [11]:
y=np.linspace(0,1,5)
print("Linspace array:",y)

Linspace array: [0.   0.25 0.5  0.75 1.  ]


#### Randomization

In [16]:
# Random numbers array
rand_array = np.random.rand(2,3)
print("random array\n",rand_array)

random array
 [[0.63122817 0.85858479 0.91479378]
 [0.97344289 0.25050818 0.67554833]]


In [17]:
# Normal distribution array
norm_dist=np.random.randn(2,3)
print("Normal Array:\n",norm_dist)

Normal Array:
 [[ 1.66781887  0.09243047  0.87083315]
 [-0.88799786  0.17502711  1.38783788]]


In [18]:
# Random Integers 
random_integers = np.random.randint(0,10,(2,3))
print("Random Integers Array: \n",random_integers)

Random Integers Array: 
 [[3 7 6]
 [9 5 0]]


#### Indexing and slicing

In [19]:
array = np.array([[1,2,3],[4,5,6]])
print("original array:\n",array)
print("Element at (0,1):",array[0,1])

original array:
 [[1 2 3]
 [4 5 6]]
Element at (0,1): 2


#### Slicing operations

In [21]:
subarray= array[0,:2]
print("sliced subarray:",subarray)

sliced subarray: [1 2]


#### Array Operations

In [22]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
print("Addition",array1 + array2)
print("Multiplication:",array * array2)

Addition [5 7 9]
Multiplication: [[ 4 10 18]
 [16 25 36]]


In [23]:
mat = np.array([[1,2],[3,4]])
vect = np.array([10,20])
print("Broadcasted Addition:\n",mat+vect)

Broadcasted Addition:
 [[11 22]
 [13 24]]


#### Reshaping arrays

In [26]:
# Reshaping Array 
reshaped = np.arange(6).reshape((2,3))
print("Reshaped Array:\n",reshaped)

Reshaped Array:
 [[0 1 2]
 [3 4 5]]


#### Advanced functionalities 

In [28]:
# Linear Algebra 
mat = np.array([[1,2],[3,4]])
vect = np.array([10,20])
print("dot product:\n",np.dot(mat, vect))

dot product:
 [ 50 110]


In [30]:
# Statistical Computations
stat_array=np.array([1,2,3,4,5])
print("Mean:",np.mean(stat_array))
print("Standard Deviation:",np.std(stat_array))

Mean: 3.0
Standard Deviation: 1.4142135623730951
